# fly.toml app configuration file generated for rairu-kun on 2025-05-06T05:15:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tngrox'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
